server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.servlet.encoding.charset=UTF-8

spring.application.name=user-api
server.port=10348

spring.profiles.active=dev

eureka.client.service-url.defaultZone=http://localhost:10344/eureka,http://localhost:10345/eureka