server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.servlet.encoding.charset=UTF-8

spring.application.name=user-api
server.port=10348

# Config Server 설정을 가져옴 (Eureka 연동 시 주소 생략)
spring.config.import=optional:configserver:
# Eureka 등 서비스 디스커버리로 Config Server 위치 탐색 활성화
spring.cloud.config.discovery.enabled=true
# Eureka에 등록된 Config Server의 서비스 이름
spring.cloud.config.discovery.service-id=config-server
# 가져올 설정 파일 이름(naver-api.yml 등)
spring.cloud.config.name=mysql

spring.profiles.active=dev

eureka.client.service-url.defaultZone=http://localhost:10344/eureka,http://localhost:10345/eureka