server.port=10348

# 한글 깨짐 현상을 막기 위한 설정
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.servlet.encoding.charset=UTF-8

spring.application.name=user-api
spring.profiles.active=dev

eureka.client.service-url.defaultZone=http://localhost:10344/eureka,http://localhost:10345/eureka

# Config Server 설정을 가져옴 (Eureka 연동 시 주소 생략)
spring.config.import=optional:configserver:

# Eureka 등 서비스 디스커버리로 Config Server 위치 탐색 활성화
spring.cloud.config.discovery.enabled=true

# Eureka에 등록된 Config Server의 서비스 이름
spring.cloud.config.discovery.service-id=config-server

# 가져올 설정 파일 이름 및 프로필
spring.cloud.config.name=mysql

# DBCP2 적용
spring.datasource.type=org.apache.commons.dbcp2.BasicDataSource

spring.datasource.dbcp2.initial-size=5
spring.datasource.dbcp2.max-total=20
spring.datasource.dbcp2.max-idle=10
spring.datasource.dbcp2.min-idle=5
spring.datasource.dbcp2.validation-query=SELECT 1
spring.datasource.dbcp2.test-on-borrow=true

# jpa 서버 시간 설정
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
