### 주소등록
POST http://localhost:10348/users/address
Content-Type: application/json

{
  "addressNickName": "주소1",
  "addressDetail": "광주광역시 상무대로 123",
  "userId": "test"
}

### 주소 조회
GET http://localhost:10348/users/address/1
Content-Type: application/json

### 주소 조회(회원별)
GET http://localhost:10348/users/address/user/test
Content-Type: application/json

### 주소 삭제
DELETE http://localhost:10348/users/address/1