### 주소등록
POST http://localhost:10348/users/address
Content-Type: application/json

{
  "addressNickName": "직장",
  "addressDetail": "nhn아카데미",
  "userId": "admin"
}

### 주소 조회
GET http://localhost:10348/users/address/1
Content-Type: application/json

### 주소 조회(회원별)
GET http://localhost:10348/users/address/user/test
Content-Type: application/json

### 주소 삭제
DELETE http://localhost:10348/users/address/1