### 장바구니 생성 (회원)
POST http://localhost:10348/carts/me
Content-Type: application/json
X-OWNER-TYPE: USER
X-USER-ID: test

### 장바구니 조회 (회원)
GET http://localhost:10348/carts/me
Content-Type: application/json
X-OWNER-TYPE: USER
X-USER-ID: test

### 장바구니 생성 (비회원)
POST http://localhost:10348/carts/me
Content-Type: application/json
X-OWNER-TYPE: GUEST

### 장바구니 조회 (비회원)
GET http://localhost:10348/carts/me
Content-Type: application/json
X-OWNER-TYPE: GUEST
X-GUEST-UUID: 90f5d15e-2de0-49d0-8060-0624747d376d

### 장바구니 추가 (회원)
POST http://localhost:10348/carts/me/items
Content-Type: application/json
X-OWNER-TYPE: USER
X-USER-ID: test

{
  "itemId": 10,
  "quantity": 1
}

### 장바구니 삭제 (회원)
DELETE http://localhost:10348/carts/me/items/10
Content-Type: application/json
X-OWNER-TYPE: USER
X-USER-ID: test
