### 장바구니 추가

POST http://localhost:10348/carts/me
Content-Type: application/json
X-USER-ID: test

{
  "userId": "test",
  "bookId": 1,
  "quantity": 2
}

### 장바구니 추가2
POST http://localhost:10348/carts/me
Content-Type: application/json
X-USER-ID: admin

{
  "userId": "admin",
  "bookId": 3,
  "quantity": 1
}

### 장바구니 추가3
POST http://localhost:10348/carts/me
Content-Type: application/json
X-USER-ID: test1

{
  "userId": "test1",
  "bookId": 3,
  "quantity": 3
}

### 장바구니 조회
GET http://localhost:10348/carts/me
Content-Type: application/json
X-USER-ID: test


### 장바구니 조회2
GET http://localhost:10348/carts/me
Content-Type: application/json
X-USER-ID: test1

### 장바구니 수정
PUT http://localhost:10348/carts/me/1
Content-Type: application/json
X-USER-ID: test

{
  "quantity": 5
}

### 장바구니 삭제
DELETE http://localhost:10348/carts/me/1
Content-Type: application/json
X-USER-ID: test

### 장바구니 삭제2
DELETE http://localhost:10348/carts/me/2
Content-Type: application/json
X-USER-ID: admin

### 장바구니 삭제3
DELETE http://localhost:10348/carts/me/3
Content-Type: application/json
X-USER-ID: test1

### 장바구니 조회(단건)
GET http://localhost:10348/carts/me/1
Content-Type: application/json
X-USER-ID: test

### 장바구니 조회(단건2)
GET http://localhost:10348/carts/me/2
Content-Type: application/json
X-USER-ID: admin

### 장바구니 삭제 - 유저
DELETE http://localhost:10348/carts/me
Content-Type: application/json
X-USER-ID: test