### 비회원 등록
POST http://localhost:10348/guests/register
Content-Type: application/json

{
  "guestPassword": "1234",
  "guestName": "비회원",
  "guestPhoneNumber": "010-1234-5678",
  "guestAddress": "조선대학교",
  "guestEmail": "test@test.com"
}

### 비회원 조회
GET http://localhost:10348/guests/test@test.com
Content-Type: application/json

### 비회원 삭제
DELETE http://localhost:10348/guests/test@test.com

### 비회원 정보 수정
PUT http://localhost:10348/guests/test@test.com
Content-Type: application/json

{
  "guestPassword": "12345",
  "guestName": "테스트",
  "guestPhoneNumber": "010-1234-5678",
  "guestAddress": "서울대학교"
}