### 비회원 등록
POST http://localhost:10348/guests/register
Content-Type: application/json

{
  "guestPassword": "1234",
  "guestName": "테스트",
  "guestAddress": "조선대학교",
  "guestEmail": "test@test.com",
  "guestPhoneNumber": "010-1234-5678"
}