### 주문 후 포인트 적립
POST localhost:10348/users/order-point/52/plus
Content-Type: application/json

{
  "orderNo": 1,
  "purePrice": 10000
}

### 주문 시 포인트 사용
POST localhost:10348/users/order-point/52/minus
Content-Type: application/json

{
  "orderNo": 1,
  "usePoint": 1000
}