### 유형별 적립포인트 등록 1
POST http://localhost:10348/users/pointType
Content-Type: application/json

{
  "typeName": "리뷰작성",
  "earningPoint": 500,
  "earningRate": 0,
  "gradeName": "PLATINUM"
}

### 유형별 적립포인트 등록 2
POST http://localhost:10348/users/pointType
Content-Type: application/json

{
  "typeName": "리뷰작성",
  "earningPoint": 500,
  "earningRate": 1,
  "gradeName": "BASIC"
}

### 유형별 적립포인트 등록 3
POST http://localhost:10348/users/pointType
Content-Type: application/json

{
  "typeName": "순수금액별 포인트 적립",
  "earningPoint": 0,
  "earningRate": 4,
  "gradeName": "PLATINUM"
}

### 유형별 적립포인트 조회
GET http://localhost:10348/users/pointType?gradeName=BASIC
Content-Type: application/json

### 모든 적립포인트 조회
GET http://localhost:10348/users/pointType

### 유형 식별키를 이용해 유형별 적립포인트 내역 삭제
DELETE http://localhost:10348/users/pointType/3

### 유형에 따른 적립포인트 포인트 수정 수정
PUT http://localhost:10348/users/pointType/1/point?point=300

### 유형에 따른 적립포인트 적립률 수정
PUT http://localhost:10348/users/pointType/1/rate?rate=0
