### 포인트 내역 등록
POST http://localhost:10348/users/point
Content-Type: application/json

{
  "userId": "test",
  "typeId": 1,
  "paymentId": 1,
  "earnedAndUsedAt": "2012-02-14 14:51:05",
  "earnedAndUsedPoint": 5000
}

### 해당 유저의 포인트 내역 조회
GET http://localhost:10348/users/point/test
Content-Type: application/json