### 리뷰등록(사진x)

POST http://localhost:10348/reviews/me
Content-Type: application/json
X-USER-ID: test

{
  "evaluationScore": 5,
  "reviewContent": "정말 재밌어요!",
  "userId": "test",
  "bookId": 120
}


### 리뷰등록(사진O)

POST http://localhost:10348/reviews/me
Content-Type: application/json
X-USER-ID: test

{
  "evaluationScore": 5,
  "reviewContent": "정말 재밌어요!",
  "imageUrls": [
    "https://example.com/image1.jpg",
    "https://example.com/image2.jpg"
  ],
  "userId": "test",
  "bookId": 149
}

### 리뷰등록2

POST http://localhost:10348/reviews/me
Content-Type: application/json
X-USER-ID: test

{
  "evaluationScore": 3,
  "reviewContent": "정말 슴슴해요!",
  "reviewPhoto": "",
  "userId": "test",
  "bookId": 2
}

### 리뷰등록3

POST http://localhost:10348/reviews/me
Content-Type: application/json
X-USER-ID: test1

{
  "evaluationScore": 1,
  "reviewContent": "정말 재미없어요!",
  "reviewPhoto": "",
  "userId": "test1",
  "bookId": 1
}

### 리뷰등록4

POST http://localhost:10348/reviews/me
Content-Type: application/json
X-USER-ID: test

{
  "evaluationScore": 5,
  "reviewContent": "이거 정말 재밌어요!",
  "reviewPhoto": "",
  "userId": "test",
  "bookId": 2
}


### 리뷰등록5

POST http://localhost:10348/reviews/me
Content-Type: application/json
X-USER-ID: test1

{
  "evaluationScore": 3,
  "reviewContent": "정말 보통이에요!",
  "reviewPhoto": "",
  "userId": "test1",
  "bookId": 2
}


### 리뷰수정
PUT http://localhost:10348/reviews/me/51
Content-Type: application/json
X-USER-ID: test

{
  "evaluationScore": 4,
  "reviewContent": "조금 아쉬웠어요.",
  "imageUrls": [
    "https://example.com/image1.jpg",
    "https://example.com/image2.jpg"
  ]
}

### 리뷰조회(단건)
GET http://localhost:10348/reviews/3
Content-Type: application/json

### 리뷰조회(유저별)
GET http://localhost:10348/reviews/user/test
Content-Type: application/json

### 리뷰조회(책별)
GET http://localhost:10348/reviews/book/1
Content-Type: application/json

### 리뷰사진 bucket생성
POST http://localhost:10348/minio/bucket


### 책당 리뷰 수 조회
GET http://localhost:10348/reviews/book/1/count

### 책당 리뷰 평균 평점 조회
GET http://localhost:10348/reviews/book/1/average-score