### 회원 등록
POST http://localhost:10348/users/register
Content-Type: application/json

{
  "userId": "test",
  "userPassword": "12345",
  "userName": "test",
  "userPhoneNumber": "010-1234-5678",
  "userEmail": "test@test.com",
  "userBirth": "2025-06-09"
}

### 회원 조회
GET http://localhost:10348/users/test
Accept: application/json

### 회원 삭제
DELETE http://localhost:10348/users/test

### 회원 인적사항 수정
PUT http://localhost:10348/users/test/personalinformation
Content-Type: application/json

{
  "userId": "test",
  "userPassword": "12345",
  "userName": "test",
  "userPhoneNumber": "010-1234-5678",
  "userEmail": "test@test12345.com",
  "userBirth": "2025-06-09"
}

### 회원 마지막 로그인 날짜 수정
PUT http://localhost:10348/users/test/lastloginat

### 회원 포인트 수정
PUT http://localhost:10348/users/test?point=500
Content-Type: application/json

### 회원 상태 수정
PUT http://localhost:10348/users/test/status?status=WITHDRAWN
Content-Type: application/json

### 회원 등급 수정
PUT http://localhost:10348/users/test/grade?gradeName=ROYAL
Content-Type: application/json




