### 회원 등록
POST http://localhost:10348/users/register
Content-Type: application/json

{
  "userId": "admin",
  "userPassword": "test125",
  "userName": "test125",
  "userPhoneNumber": "010-3333-2222",
  "userEmail": "test@test.com",
  "userBirth": "2020-03-12"
}

### 아이디찾기
GET http://localhost:10348/users/findId?userName=test1&userEmail=test@test.com

### 회원 등록(OAuth2)
POST http://localhost:10348/users/register/oauth2
Content-Type: application/json

{
  "provider" : "PAYCO",
  "providerId" : "142421-123df-11e4-000003ef34",
  "userName" : "성이름",
  "userPhoneNumber" : "010-1234-5678"
}

### 회원 조회
GET http://localhost:10348/users/me
Accept: application/json
X-USER-ID: PAYCO142421-123df-11e4-000003ef34

### 회원 조회
GET http://localhost:10348/users/PAYCO142421-123df-11e4-000003ef34
Accept: application/json

### 회원 조회(유저번호)
GET http://localhost:10348/users/user/1
Accept: application/json

### 회원 삭제
PUT http://localhost:10348/users/me/status/WITHDRAWN
X-USER-ID: PAYCO142421-123df-11e4-000003ef34

### 회원 인적사항 수정
PUT http://localhost:10348/users/me/personalinformation
Content-Type: application/json
X-USER-ID: PAYCO142421-123df-11e4-000003ef34

{
  "userName": "바뀐성이름",
  "userPhoneNumber": "010-1234-5678",
  "userEmail": "test@test12345.com",
  "userBirth": "2025-06-09"
}

### 회원 마지막 로그인 날짜 수정
PUT http://localhost:10348/users/me/lastloginat
X-USER-ID: PAYCO142421-123df-11e4-000003ef34

### 회원 상태 수정
PUT http://localhost:10348/users/me/status?status=WITHDRAWN
Content-Type: application/json
X-USER-ID: withdrawnUser

### 회원 전체등급 수정
PUT http://localhost:10348/users/bulk/grade
Content-Type: application/json

### 회원 포인트 조회
GET localhost:10348/users/me/my-point
Content-Type: application/json
X-USER-ID: ttestt

### 회원 포인트 적립
PUT localhost:10348/users/me/plus-point?point=5000
Content-Type: application/json
X-USER-ID: ttestt

### 회원 포인트 차감
PUT localhost:10348/users/me/minus-point?point=3000
Content-Type: application/json
X-USER-ID: ttestt
