### 등급 추가(기본)
POST http://localhost:10348/users/grade
Content-Type: application/json

{
  "gradeName": "BASIC",
  "requiredMoney": 0
}

### 등급추가(로얄)
POST http://localhost:10348/users/grade
Content-Type: application/json

{
  "gradeName": "ROYAL",
  "requiredMoney": 100000
}

### 등급추가(골드)
POST http://localhost:10348/users/grade
Content-Type: application/json

{
  "gradeName": "GOLD",
  "requiredMoney": 200000
}

### 등급추가(플래티넘)
POST http://localhost:10348/users/grade
Content-Type: application/json

{
  "gradeName": "PLATINUM",
  "requiredMoney": 300000
}

### 등급조회
GET http://localhost:10348/users/grade/BASIC
Content-Type: application/json

### 등급조회(전체)
GET http://localhost:10348/users/grade/all
Content-Type: application/json

### 등급수정
PUT http://localhost:10348/users/grade/ROYAL
Content-Type: application/json

{
  "gradeName": "ROYAL",
  "requiredMoney": 1800000
}

### 등급삭제
DELETE http://localhost:10348/users/grade/BASIC


