### 회원 등록
POST http://localhost:10348/users/register
Content-Type: application/json

{
  "userId": "newTest",
  "userPassword": "12345",
  "userName": "test",
  "userPhoneNumber": "010-3333-2222",
  "userEmail": "test@test.com",
  "userBirth": "2020-03-12"
}

### 회원 조회
GET http://localhost:10348/users/me
Accept: application/json
X-USER-ID: newTest

### 회원 삭제
DELETE http://localhost:10348/users/me
X-USER-ID: newTest

### 회원 인적사항 수정
PUT http://localhost:10348/users/me/personalinformation
Content-Type: application/json
X-USER-ID: newTest

{
  "userPassword": "12345",
  "userName": "newTest",
  "userPhoneNumber": "010-1234-5678",
  "userEmail": "test@test12345.com",
  "userBirth": "2025-06-09"
}

### 회원 마지막 로그인 날짜 수정
PUT http://localhost:10348/users/me/lastloginat
X-USER-ID: newTest

### 회원 포인트 수정
PUT http://localhost:10348/users/me/point?point=10000
Content-Type: application/json
X-USER-ID: newTest

### 회원 상태 수정
PUT http://localhost:10348/users/me/status?status=WITHDRAWN
Content-Type: application/json
X-USER-ID: withdrawnUser

### 회원 등급 수정
PUT http://localhost:10348/users/me/grade?gradeName=PLATINUM
Content-Type: application/json
X-USER-ID: admin




